### PR TITLE
Create pl_pl.json

### PR DESCRIPTION
**Pull request by K0-RR**

### CODE REVIEW

**Comment by LambdAurora** [comment]
@Patbox you might want to check this if you have time.

**Comment by K0-RR** [comment]
The only thing I haven't done is to check how these translations fit in the GUI. Wanted to do this after I complete translating other mods.

**Comment by Patbox** [comment]
2 strings aren't translated (`nourish.command.value`/`nourish.command.set`), but generally it looks fine. I still need to check context of some messages, as they could differ a little from intended one

**Comment by Hubry** [comment]
Singular fruit instead of plural there for the food group? (Especially with the example screenshot in repo readme using plurals.)
I feel like `odżywienie` instead of `pożywienie` would fit better in that context, and `drugorzędny` probably should be `drugorzędne` instead.

**Comment by K0-RR** [comment]
>Singular fruit instead of plural there for the food group? 

That's because I was kinda confused why it is `fruit` instead of `fruits`, To be honest, I didn't know `fruit` is both plural and singular and wanted to report this as a typo. Today I found this https://english.stackexchange.com/questions/25147/is-using-fruits-as-the-plural-of-fruit-acceptable. Also, what with the word `protein`? Shouldn't it be `proteins`? https://en.wikipedia.org/wiki/Protein
Edit: "Nouns for classes of foodstuff (fruit, meat, cheese, etc.) are usually uncountable, but they take a countable sense when we talk about different varieties (a wide selection of cold meats and cheeses)."
>drugorzędny probably should be drugorzędne instead.

Totally
>odżywienie instead of pożywienie

I wasn't sure about this one, maybe something not 1:1? Like `Składniki odżywcze`.

**Comment by Hubry** [comment]
> Like `Składniki odżywcze`.

Heck yes.

> Shouldn't it be `proteins`? 

Quick googling seems to tell me that in the context of food substances it can be treated as uncountable where you just use the singular form.

**Comment by K0-RR** [comment]
> 2 strings aren't translated

I don't know where these are displayed but 

"nourish.command.value": "Grupa %d jest na poziomie %d",
"nourish.command.set": "Grupa %d jest ustawiona na %d",

would be `Grupa Tłuszcze jest na poziomie`  instead of `Grupa tłuszczy jest na poziomie`

**Comment by Hubry** [comment]
I think it would actually be `Grupa fats jest na poziomie`, internal names seem to be used there. It's for the `nourish` command.

**Comment by K0-RR** [comment]
What about
	"nourish.group.description.sweets": "Zbyt wiele słodyczy jest dla ciebie szkodliwe!"
to
	"nourish.group.description.sweets": "Zbyt dużo słodkiego jest dla ciebie szkodliwe!"
?

**Comment by K0-RR** [comment]
"Zbyt dużo słodyczy ci szkodzi"?

**Review by Hubry — APPROVED** [review]
I feel like the singular `Białko` should be used there, but this looks good to me.

**Pull request merged**
